### ISSUE TITLE
Change text, color theme, set initial value on open

### ISSUE THREAD

**Issue by topex-psy** [adawoud/BottomSheetTimeRangePicker#5]
I've just use this library. It's good in my opinion. Please add customization options for changing "start time", "end time" and "done" label, clock text size, color theme. Also how to set initial time value for both start & end? I want like open/beforeOpen listener and there I set the value to match current variable. Thank you.

**Comment by adawoud** [comment]
@topex-psy thanks for the suggestion. I'll push out an update adding this soon.

**Comment by adawoud** [comment]
@topex-psy I pushed out an [update](https://github.com/adawoud/BottomSheetTimeRangePicker/pull/6) to add these features. You can now download v1.1 of the library.

**Comment by topex-psy** [comment]
Thank you! But there's one more issue. When I touch outside the circle of the clock (e.g I want to drag to expand the dialog), the time changed. Can you remove touch input when I touch outside the circle?
And please add option for button margin & to open second tab on init.
