### ISSUE TITLE
Prevent input when touch outside the clock & button customization

### ISSUE THREAD

**Issue by topex-psy** [adawoud/BottomSheetTimeRangePicker#7]
When I touch outside the circle of the clock (e.g I want to drag to expand the dialog), the time changed. Can you remove touch input when I touch outside the circle?
And also please add option for button `margin`, `drawable`, `drawablePadding` & to open second tab first.

**Comment by adawoud** [comment]
>When I touch outside the circle of the clock (e.g I want to drag to expand the dialog), the time changed. Can you remove touch input when I touch outside the circle?

This is the default behavior of the stock TimePicker.

>And also please add option for button margin, drawable, drawablePadding

The buttons have a margin of 16dp as of now--I think this works out well. I'll look into adding drawable and drawable padding in a future release. Thanks for the suggestion.

>& to open second tab first.

But why?

**Comment by topex-psy** [comment]
> This is the default behavior of the stock TimePicker.

Then could you give option to set height for the opened bottom sheet, or making it to fully extended automatically? Because in my phone, I have to drag up the bottom sheet to have the content (the button) fully visible. When I drag up, it messed up the clock.

> > & to open second tab first.
> 
> But why?

In my case, I use this library for setting open & close hour for store/business. I give user like two pencil icon to edit both open hour & close hour, thus I want it to have second tab opened when user click edit for closing hour.
