### ISSUE TITLE
 endTimeInitialHour  is  wrong !!

### ISSUE THREAD

**Issue by FidanBacaj** [adawoud/BottomSheetTimeRangePicker#8]
After  i  saw the libraries code i saw one problem in function :  initInitialTimeValuesIfAdjusted()  the endMinute was set for both (endHours and endMinute).

I just wanted to report this problem.

**Comment by CeccoCQ** [comment]
Same issue here.

**Comment by adawoud** [comment]
Hi, thanks for reporting this issue. I'm currently away but I'll push out an update to fix it next week. You're welcome to fix this yourself and make a pull request right now if you'd like to.

**Comment by adawoud** [comment]
This issue has been fixed [here](https://github.com/adawoud/BottomSheetTimeRangePicker/pull/10). I'm sorry for the delay.
